name: CI
on: push
env:
  MIX_ENV: test
  ELIXIR_VERSION: 1.12
  ERLANG_VERSION: 24

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: trans_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup CI test configuration
        run: cp config/test.ci.exs config/test.exs
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.ERLANG_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - name: Retrieve dependencies cache
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-erlang-${{ env.ERLANG_VERSION }}-elixir-${{ env.ELIXIR_VERSION }}-mix-${{ hashfiles('**/mix.lock') }}
      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Compile application
        run: |
          mix compile --warnings-as-erros
      - name: Check format
        run: |
          mix format --check-formatted
      - name: Run tests
        run: |
          mix test
